version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    container_name: keycloak
    command: start-dev --import-realm
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
    volumes:
      - ./keycloak-data:/opt/keycloak/data/import